# Generated by Django 3.2.20 on 2023-09-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_productgalery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgalery',
            options={'verbose_name': 'productgallery', 'verbose_name_plural': 'product gallery'},
        ),
        migrations.AddField(
            model_name='product',
            name='trending',
            field=models.BooleanField(default=False, help_text='0-default,1-trending'),
        ),
    ]
