# Generated by Django 3.2.20 on 2023-09-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_orderedproduct_variation'),
        ('carts', '0006_remove_cart_item_variation'),
        ('store', '0006_auto_20230911_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
