# Generated by Django 3.2.20 on 2023-09-19 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile'),
        ('store', '0009_auto_20230918_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrating',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
    ]
