# Generated by Django 3.2.20 on 2023-09-19 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_reviewrating_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='profile',
        ),
    ]
