# Generated by Django 3.2.20 on 2023-09-12 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_auto_20230905_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_item',
            name='variation',
        ),
    ]
