# Generated by Django 3.2.20 on 2023-09-07 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20230906_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderedproduct',
            name='size',
        ),
    ]
