# Generated by Django 3.2.20 on 2023-09-07 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_variation_created_date'),
        ('orders', '0004_auto_20230907_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedproduct',
            name='variation',
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='variation',
            field=models.ManyToManyField(blank=True, to='store.Variation'),
        ),
    ]
